### ISSUE TITLE
Getting to an end point.

### ISSUE THREAD

**Issue by dicepd** [jdelauney/SIMD-VectorMath-UnitTest#1]
At some stage we are going to want to draw a line under the assembler routines but still need a library in a state where it can be used but also in a state where we can revisit routines to improve on an ongoing basis.

One suggestion I have is to take the native.inc file and wrap all pure pascal in three groups.

1: Pure Pascal: This group will never be converted to asm ( such as Create )
2: Pascal ToDo: Routines which complete the library, but we are not inclined to convert to asm for whatever reason. (Time pressures, better things to do)
3: Pascal routines which have assembler complete.

All of these groups can be placed in the vectormath_XXXX_native_imp.inc files.

The first two separated by region markers so we know what we would like to do and what we will never do.

The third separated by a region but also by an {$IFNDEF USE_ASM} block. 

This will allow a common pascal inc to be added at the top of each assembler include file which will pick up only the routines which are todo or will never do as all the assembler routines will only be entered with USE_ASM defined.

The pascal code can still be used as a stand alone include.

Benefits, all implementation code is removed from GLZVectorMath leaving it as a interface only file, with implementation consts. We would need only one ifdef USE_ASM for all inc files. 

Removal of a routine from todo to assembler will then trigger a compiler error where an assembler routine has not been implemented, aiding in not forgetting to do one part, or in the case that Jerome has done a win64 implementation is a todo marker for me when I get a pull and then know there is work to be done. 

This will allow a fully working library which Jerome could use and test against GLZScene very quickly, which also means it would be easier for him to decide early what needs to be included, as it would be usable thoughout its development cycle.

Items in the todo section could have tests prepared in advance of assembler code production as they would just pick up the pascal code in the todo section.

**Comment by jdelauney** [comment]
I right for the change with native.inc Peter. so if i understand we have only one Inc for VectorMath and Native unit ?

**Comment by dicepd** [comment]
I will make an example for quaternion to show what I mean with the includes.

**Comment by dicepd** [comment]
Ok take a look at what I have done with Quaternion there are comments around the changes.
