### ISSUE TITLE
Real Test Case : BoïdZ Demo

### ISSUE THREAD

**Issue by jdelauney** [jdelauney/SIMD-VectorMath-UnitTest#12]
I've made a little demo for testing our Vectors 

Results
- NATIVE MODE  : All work in 32 & 64 bit
- ASM_SSE_3  :   
  - Cpu32 : Nothing is displayed and a SIGFPEG is raised in the procedure RenderScene =
   ` c:=round(ArcTan2(b.UV.X,b.UV.Y)*180/cPi)+180;  `    
  - Cpu64 : All run but displayed just a line from topleft to bottomright

I think the problem is due on some out of range and surely cause from bad data alignment

Must see what is wrong,, but i don't really say how to debug and trace these "_badass_" behaviours

**Comment by dicepd** [comment]
umainform.pas(291,23) Error: identifier idents no member "ST"

      MoveTo(P.ST.x,P.ST.y);

**Comment by dicepd** [comment]
Ok finally got it working by using Mainform.Canvas direct. Can run in both 64 bit native and 64 bit SSE.

Though not much speedup.

**Comment by dicepd** [comment]
Ok a bit more testing and yes when I get the setting right to max cpu, turn cadencer down, I get more fps with SSE, but only about 20%, but I suspect most of the time is spent drawing rather than in the AnimateScene.

**Comment by jdelauney** [comment]
> Can run in both 64 bit native and 64 bit SSE. Ok a bit more testing and yes when I get the setting right to max cpu, turn cadencer down, I get more fps with SSE, but only about 20%

Ouch !!!! In win64 with SSE i'm only see a straight line from topleft to bottomleft (same case with direct Canvas)

What do you do ?????

**Comment by dicepd** [comment]
```pascal
  FBitmapBuffer.canvas.Brush.color:=clBlack;
  FBitmapBuffer.canvas.FillRect(clientrect);
  mainform.Canvas.Clear;
  for i:=0 to maxboidz do
  begin
    b := FBoidz[i];
    p := b.Round;
    //P.X:=Round(FBoidz[i].ST.X);
    //P.Y:=Round(FBoidz[i].ST.Y);

    //calcul de la direction de déplacement pour la couleur
    c:=round(ArcTan2(b.UV.X,b.UV.Y)*180/cPi)+180;
    //c:=345;
     //  CurColor := FBitmapBuffer.ColorManager.Palette.Colors[c].Value;
    CurColor := FColorMap[c];
//    with FBitmapBuffer.Canvas do
     with MainForm.Canvas do
    begin
      Pen.Style := psSolid;
      Pen.Color :=  CurColor;
      // dessine un traits de la longueur de la vitesse
      MoveTo(P.ST.x,P.ST.y);
      LineTo(P.ST.x+P.UV.x,P.ST.y+P.UV.y);
    end;
   end;
 // MainForm.Refresh;

  (* With FBitmapBuffer.Canvas do                             
```
The only code change to see the swarm.
Apart from settings for engine, only other thing I changed was I added -Sv and -O3  in the options.

**Comment by jdelauney** [comment]
What's the hell with windows, for once time ????
On Left what i can see without "-dUSE_ASM_SSE_3" options, and with on 2dn image
![2018-01-08_203750](https://user-images.githubusercontent.com/29355534/34688918-02aa42ce-f4b4-11e7-86b7-a2da3ac42e16.jpg)
![2018-01-08_203526](https://user-images.githubusercontent.com/29355534/34688919-02c4ea3e-f4b4-11e7-8047-761b95acad6e.jpg)

and with your change the windows still empty nothing is shown

it's silly !!!!!!!

**Comment by dicepd** [comment]
Let me get my windows box going, I'll get back to you if I find something.

**Comment by jdelauney** [comment]
And now wath i see with my own bitmap management without SSE3 and With

![2018-01-08_204619](https://user-images.githubusercontent.com/29355534/34689303-4a3fecf0-f4b5-11e7-9158-68051f66f12b.jpg)
![2018-01-08_203526_cr](https://user-images.githubusercontent.com/29355534/34689305-4ae4cc3e-f4b5-11e7-9f42-5e5b6b230d55.jpg)

the 2nd it the same out also with you're changes

It's really really strange !!!! I'll add a log to see the results of operations

**Comment by jdelauney** [comment]
Ok now by checking the Range checking" (-Cr) in debug options
this is what i see : 

![2018-01-08_205718](https://user-images.githubusercontent.com/29355534/34689702-c020d3de-f4b6-11e7-88f3-d6710ce6f88d.jpg)

But see the FPS !!!!!!! so something is wrong or something happens under win64 with current SSE code

**Comment by jdelauney** [comment]
i've just found this : https://software.intel.com/en-us/articles/x87-and-sse-floating-point-assists-in-ia-32-flush-to-zero-ftz-and-denormals-are-zero-daz

perhaps a beginning of answer

**Comment by dicepd** [comment]
My windows box just sees a stripe from top left to bottom right too. It is as if something is clamping it to x = y scaled to window size.

**Comment by dicepd** [comment]
Check your win64 vector4f round and trunc they are so wrong!

**Comment by jdelauney** [comment]
So i've play a bit with MXSCR register and the problem seems to come from the TGLZVector2f./
a SIGFPE is raise on the line :  `divps xmm0, xmm1` . After replace by native code it seems also have a problem with TGLZVector4f. But what ???? need more deep search

**Comment by jdelauney** [comment]
Ok you're right Peter the round function cause the problem


```
function TGLZVector4f.Round: TGLZVector4i;assembler;nostackframe;register;
asm
  // Rounding mode defaults to round-to-nearest
  movaps   xmm0, [RCX]
  cvtps2dq xmm0, xmm0
  movq     [RDX],  xmm0
end; 
```

Don't say how to fix it......

**Comment by jdelauney** [comment]
Ok finally 
```
function TGLZVector4f.Round: TGLZVector4i;assembler;//nostackframe;register;
asm
  // Rounding mode defaults to round-to-nearest
  movaps   xmm0, [RCX]
  cvtps2dq xmm0, xmm0
  movdqa   [Result],  xmm0
end;
```
This work. But to have BoidZ work i need to change this : 
class operator TGLZVector2f./(constref A, B: TGLZVector2f): TGLZVector2f; assembler; nostackframe; register;
asm
  movq  xmm0, [A]
  movq  xmm1, [B]
  divps xmm0, xmm1  // SIGFPE raise here
 movq  [Result], {%H-}xmm0
end;

by

class operator TGLZVector2f./(constref A, B: TGLZVector2f): TGLZVector2f; 
begin
  result.x := a.x /b.x;
  result.y := a.y /b.y;
end;

**Comment by jdelauney** [comment]
Ok i found the error is in the function above in SSE the divisor for Hi is not set and equal to 0 so it's normal a SIGFPE raised so the trick

```
class operator TGLZVector2f./(constref A, B: TGLZVector2f): TGLZVector2f; assembler; //nostackframe; register;
asm
  movq  xmm0, [A]
  movq  xmm1, [B]
  movlhps xmm1,xmm1 //--- Fill upper register
  divps xmm0, xmm1
  movq     RAX,  xmm0
end;
```

now is working gain is not high without asm the average FPS is 18.55 with SSE enabled FPS is 19,97

**Comment by dicepd** [comment]
Ok I profiled this with valgrind and tbh I am surprised we got any speedup. 
less than 15% of time in calls to SSE code but CheckAngleofView is the killer for this, really bad design as it ends up doing Math.ArcTan2 through another call, so there is a whole stackframe around a call to a native pascal FPU function. And this is called a lot. then directly afterwards we have a call to SSE lengthSqr. In fact this call is the bulk of the calls to the library.

So all in all probably not a good choice for a speedup demo.

**Comment by dicepd** [comment]
So a switch to the FastArcTangent2 and 18fps becomes 46fps

**Comment by dicepd** [comment]
After stripping out all the profiling and setting a window size(fps changes with size) I get ~ 33fps native and 42fps SSE

**Comment by jdelauney** [comment]
Ok after some minor changes with
- Resolution :  800x600
- Boids         : 500
- Using FastArcTangent2 instead of ArcTan2
- Decrease the timer interval to 10
With native around : 54-55 fps
With SSE3 around : 63-64 fps
so around 10% of speedup 
not bad for this simple test
