### ISSUE TITLE
Fastmath changes broke AngleBetween

### ISSUE THREAD

**Issue by dicepd** [jdelauney/SIMD-VectorMath-UnitTest#18]
As above

**Comment by jdelauney** [comment]
Ok i'm correcting the function, it's ok now. I push the code tonight after my job

**Comment by jdelauney** [comment]
I found a realy cool link https://web.archive.org/web/20161219143458/http://http.developer.nvidia.com/Cg/index_stdlib.html
for implement Step, Saturate, SmoothStep, FaceForward....

**Comment by jdelauney** [comment]
Yes Fastmath reduce precision we do approximation. A correct minimum precision for me wil be 1e-4 with a range error max of 0.0003. Put two epsilon values  it will a good thing for having a correct evaluation.
