### ISSUE TITLE
Performances and timing test

### ISSUE THREAD

**Issue by jdelauney** [jdelauney/SIMD-VectorMath-UnitTest#20]
This afternoon i took a look to the timing result and specialy to vectorHelper i saw the PointProject SSE code was slower than native. So i've optimized it. 
After the retest the functions was always around 10% slower than native
I change in VectorHelperTimingUnit the loop of the test. I replaced the for...to by a While...do and there the performance grow up and is now 10% fastest than the native. I'm already say that repeat...until or while... do have better performance. By using for..to loop it's incredible to have 20% of difference !!! uch !!!!
We have no control on this so i suggest we use a While..do loop instead of for..to for timing test. What do you think about ?

**Comment by jdelauney** [comment]
Tonight i've launched several timingtest as a result and comparing speed factor beetween each time. the result of speed factor is not approximativaly constant. For example with While..do loop and TTGLZHmgPlane.Distance (topoint) speed factor varying between around 1.2 and 4.8. It's difficult to say what the best solution. Setting apart maybe and still roll 10x the loop and calculate the average, and not sure it will give better accuracy

**Comment by dicepd** [comment]
This is probably down to the fact that cnt is a class variable not a local variable. As the tests are comparative does it really matter apart from the time to do the tests.
