### ISSUE TITLE
4f AngleBetween fails in Pascal for obtuse angles.

### ISSUE THREAD

**Issue by dicepd** [jdelauney/SIMD-VectorMath-UnitTest#22]
Compared to AngleCosine which seems to work fine.

**Comment by jdelauney** [comment]
I've 7 functionals tests breaked : Normalize, NotEquals, GTE, GT, AngleBetween, Combine2 and Combine3

**Comment by dicepd** [comment]
Yeah Just getting to some of them, done <>

**Comment by dicepd** [comment]
got the GTE and GT bug

**Comment by jdelauney** [comment]
The not equal is a hell

In test sub2 return false also if "vt2.Create(120,60,180,240);" sub1 passed and give correct result 👍 

> "OpNotEquals:Sub2 does not match ((X: 120,00000 ,Y: 60,00000 ,Z: 180,00000 ,W: 240,00000)<>(X: 120,00000 ,Y: 60,00000 ,Z: 180,00000 ,W: 240,00000))" expected: <True> but was: <False>

I've also tried 

```
  cmp    eax,$ffff
  sete   al
  movzx  eax,al  
```

it seems something wrong with eax or the zero-flag

**Comment by jdelauney** [comment]
GT also failed 

> "OpGT:Sub2  is not GT " expected: <True> but was: <False>

**Comment by dicepd** [comment]
I just test my fixes for <> and GTE and GT in win64 and they seem to work fine

**Comment by dicepd** [comment]
I just checked in the win64 changes for <> GTE and GT

**Comment by jdelauney** [comment]
i've made changes same errors

**Comment by dicepd** [comment]
Just checked in finally had a merge issue I took no notice of when I pusher earler

**Comment by jdelauney** [comment]
Ok all is right now 👍

**Comment by jdelauney** [comment]
Always 4 functionals tests failed

- "Normalize:Sub1 X failed " expected: <0> but was: <-922337203685478>
- "AngleBetween:Sub14 -X->XY failed " expected: <2,3562> but was: <-0,7854>
- "Combine2:Sub1 X failed " expected: <26> but was: <0>
- "Combine3:Sub1 X failed " expected: <46> but was: <0>

**Comment by dicepd** [comment]
I am looking at Normalize I think I may have a way to make this hmg safe and be efficient.

**Comment by jdelauney** [comment]
Seems have some error in functionnal test case in anglebetween

```
  fs1 := XHmgVector.AngleBetween(-XYHmgVector,NullHmgPoint);
  AssertEquals('AngleBetween:Sub14 -X->XY failed ', (3*pi/4), fs1);
  fs1 := -XHmgVector.AngleBetween(XHmgVector,NullHmgPoint);
  AssertEquals('AngleBetween:Sub15 X->XY failed ', (pi), fs1);
  fs1 := -YHmgVector.AngleBetween(YHmgVector,NullHmgPoint);
  AssertEquals('AngleBetween:Sub16 X->XY failed ', (pi), fs1);
  fs1 := -ZHmgVector.AngleBetween(ZHmgVector,NullHmgPoint);
  AssertEquals('AngleBetween:Sub17 X->XY failed ', (pi), fs1);

```

**Comment by jdelauney** [comment]
For sub14 right test is

`fs1 := XHmgVector.AngleBetween(-XYHmgVector,NullHmgPoint);  `

**Comment by dicepd** [comment]
So it is winding oriented?

**Comment by dicepd** [comment]
Ok I can get Normalize working but I don't like the fact I have to put a jump in.
I do like the getting rid of 2 long masks and hmg safe.
```
  movaps xmm0, [RDI]
  movaps xmm3, xmm0
  mulps  xmm3, xmm3
  mov eax, $3f800000      // integer equiv of 1.0
  movd xmm1, eax
  shufps xmm1, xmm1, $00
  movhlps xmm1, xmm3        //  |Z^2|*|1|1|
  haddps xmm3, xmm3
  addss  xmm1, xmm3         //  |x^2 + y^2 + z^2|*|1|1|
  sqrtps xmm1, xmm1         //  |Sqrt(x^2 + y^2 + z^2)|*|1|1|
  movd  eax, xmm1            // test for 0 divisor
  add   eax, eax                 // get rid of sign bit if it exists
  jz @origin
  shufps xmm1, xmm1, 11000000b   // |sqrt(Norm)|sqrt(Norm)|sqrt(Norm)|1|
  divps  xmm0, xmm1        // divide self by above and it does not matter what W is 0/1=0  1/1=1 34/1=34   
@origin:
  movhlps xmm1, xmm0                            
```
What do you think? This is only SSE3 atm.

**Comment by dicepd** [comment]
Ok please verify this yourself, before you make the above change for win64, do a timing test.
I had SF of 1.46 from previous run before this change and now have a SF of 5.231 with the above Normalize code. Run times for native are the same in both tests.

**Comment by dicepd** [comment]
Ok final code marginally faster than previous and safe

```
  // 3 reg usage so could unroll loops 5 at a time in 64bit
  movaps  xmm0, [RDI]
  movaps  xmm2, xmm0
  mulps   xmm2, xmm2
  movaps  xmm1, [RIP+cOneVector4f]
  movhlps xmm1, xmm2        //  |Z^2|*|1|1|
  haddps  xmm2, xmm2
  addss   xmm1, xmm2         //  |x^2 + y^2 + z^2|*|1|1|
  sqrtps  xmm1, xmm1         //  |Sqrt(x^2 + y^2 + z^2)|*|1|1|
  movd    eax,  xmm1
  add     eax,  eax            // get rid of sign bit if it exists
  jz @origin
  shufps  xmm1, xmm1, 11000000b  // |sqrt(Norm)|sqrt(Norm)|sqrt(Norm)|1|
  divps   xmm0, xmm1
@origin:
  movhlps xmm1, xmm0          // sf 5.48

``

**Comment by jdelauney** [comment]
Ok Peter i've made change Perp and Normalize are now ok
but have always error with TGLZVector4f in functionals test with Combine2 and Combine3

"Combine2:Sub1 X failed " expected: <26> but was: <0>
"Combine3:Sub1 X failed " expected: <46> but was: <0>

**Comment by dicepd** [comment]
i'll fire up the win64 box after lunch and have a look

**Comment by dicepd** [comment]
Fixed too many params to use nostackframe in Win64

**Comment by jdelauney** [comment]
Ok thanks Peter i didn't check the s file. Now all are green 👍
