### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by neurolabusc** [jdelauney/SIMD-VectorMath-UnitTest#3]
With a few changes to {$IFDEF LINUX} to {$IFDEF UNIX} and changes in the project options, I was able to get this project to compile on MacOS using the Cocoa Widgetset (to get 64 bit support), however it did generate an exception when running. As a feature request, MacOS support would be handy.

**Comment by dicepd** [comment]
hmm where are the ifdef Linux? I thought we had settled on using Unix as I have been testing  earlier versions on FreeBSD. I don't have a Mac but in the past if it works on FreeBSD it generally works for a Mac. Will get out the FreeBSD box and have a look.

**Comment by neurolabusc** [comment]
I changed 9 instances of GLZSystem.pas from {$IFDEF LINUX} to {$IFDEF UNIX}

**Comment by dicepd** [comment]
Ok checked in try what is there now!

**Comment by dicepd** [comment]
No further comments on this closed

**Comment by neurolabusc** [comment]
The current code requires one modification of GLZSystem.pas to compile on MacOS. Specifically, on line 183 the text
  {$IFDEF UNIX} 
must be reverted back to 
  {$IFDEF LINUX}  
With this change, the "Native_CONFIG_1" build passes all tests when compiled as 64-bit targeting the Cocoa widgetset.

**Comment by dicepd** [comment]
Done. thank you.
