### ISSUE TITLE
Vector 2i

### ISSUE THREAD

**Issue by dicepd** [jdelauney/SIMD-VectorMath-UnitTest#31]
I have checked in first functional tests for 2i, had to add a helper just for Normalize as integer normals just do not exist and only way to get AngleBetween working. 

Not bothering with separate file for this at the moment as there are so few methods we are putting in this helper. 

Win64 broken but I have coded working code in unix64, copy away :)

**Comment by jdelauney** [comment]
Ok all vector2i are break for now (25 tests failed)

**Comment by jdelauney** [comment]
All is fixed and green
