### ISSUE TITLE
re: Test Grouping

### ISSUE THREAD

**Issue by dicepd** [jdelauney/SIMD-VectorMath-UnitTest#4]
Jerome,

I added some grouping for tests and results.

In addition if you wish you could do something like
`
initialization
  RegisterTest(REPORT_GROUP_VECTOR4F+'/Timimg', TVectorOperatorsTimingTest);                       
`
if you want timings to be deselected with one hit inside a group.

The consts in base test are mainly for grouping reports in a dir. Could be separated from visual grouping (as in above). Atm there is no easy way to say no timings for all tests without using something like ifdefs around timing registration or somehow changing the way the test runner works.

As usual change as you see fit.

**Comment by dicepd** [comment]
Ok I got a bit fed up with not being able to turn off timing tests easily, so in lpr is a define, commented out, which will turn all timing tests off.

Very useful when trying to go through all test builds to see what is broken.

**Comment by jdelauney** [comment]
Hi Peter Happy new year !

I love the groups :)it's clearly useful
