### ISSUE TITLE
TGLZHmgPlane

### ISSUE THREAD

**Issue by dicepd** [jdelauney/SIMD-VectorMath-UnitTest#5]
Jerome,

I am trying to use TGLZHmgPlane in the tests for AABBs. 

Using it in it's present form as a simple typecast of  TGLZVector just sort of feels wrong as I try to code an instance for use with AABB.ToClipRect. Looking through the code we do not at present use a TGLZHmgPlane that uses methods of TGLZVector.

Would it not be cleaner to have its own record with AsVector for the occasions where a vector operation is useful.

With advanced records there is no performance hit in using AsXXX as the asm generated by Vector4b.Divide2 shows.

It would remove the VectorHelper reliance.

You obviously know more about where this is used through the larger code base so just a thought!

**Comment by jdelauney** [comment]
Peter yes i thought also to make tglzhmgplane independant. At thks stage i m note use yet in my code. And for GLSene i need to  converting some functions  to  see. It will  be not "pertub" the code to split it
