### ISSUE TITLE
Stack Alignment

### ISSUE THREAD

**Issue by dicepd** [jdelauney/SIMD-VectorMath-UnitTest#6]
I thing we may have hit a roadblock with SSE in fpc. At least with using movaps.

Testing the VectorHelpers I came across a SIGSEGV in MoveAround.

This routine does some calls on local vars which are returned on the stack. However looking at the stack address this is not aligned to 16 bytes.

Forum post on subject of something similar, :link: https://forum.lazarus.freepascal.org/index.php?topic=29097.0

Bug report in fpc :link: https://bugs.freepascal.org/view.php?id=32710#c104254

**Comment by dicepd** [comment]
Ok so {$CODEALIGN LOCALMIN=16}  cures it in GLZVectorMath but not using that at a more granular level, all or nothing.

**Comment by dicepd** [comment]
I will check the tests in so you can play in win64 see if the behaviour is different.

**Comment by jdelauney** [comment]
I check with and without  {$CODEALIGN LOCALMIN=16} the  MoveAround. is correct with EPSILON 1e-5 in compare under win64

**Comment by dicepd** [comment]
It works for me also just doing the comparator test but if I run the timing test for this this is when I get the stack alignment problem.

**Comment by jdelauney** [comment]
I didn t see any problems with timing test. I ll redo test this afternoon

**Comment by jdelauney** [comment]
This afternoon, while i m fixing  asm for vector4i. When i ran timing test it raise a sigsegv with multiply Regarding your last issue. In our test our A parameter is Self . So i think fpc unrolled the for..to loop in case of a multiply. It must be push Self on stack for optimzing. And we need to use unaligned load functions. I don t check if is right.

**Comment by jdelauney** [comment]
Now the question how can we said when Arg is repushed on stack ?

**Comment by dicepd** [comment]
Just check the timing test for 4i I have not included 
```pascal
{$CODEALIGN RECORDMIN=16} 
```
in the class vars in the checked in code. That may cure your 4i issue.

**Comment by jdelauney** [comment]
It's corrected and work
