### ISSUE TITLE
TGLZVector2/4f  and the trunc 

### ISSUE THREAD

**Issue by jdelauney** [jdelauney/SIMD-VectorMath-UnitTest#8]
The round function work good. But with trunc the access to the SSE States in MXCSR register cause a SIGSEV when try to store the currents flag. "stmxcsr  _bakMXCSR" (see in TGLZVector4f)  and  without do this but instead taking _OldMXCSR global (see in TGLZVector2f) for comparing.  FPC compiler  return an error without any clues.

**Comment by jdelauney** [comment]
Ok i found the way for it work  But with TGLZVector4i's timing test the MulDiv and Combine who uses **Trunc** it raised a SIGFPE.

**Comment by dicepd** [comment]
Missed this post see issue #10
